-- 1. Crear la tabla de compras (con columna categoria)
CREATE TABLE compras (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha DATE DEFAULT CURRENT_DATE,
  hora TIME DEFAULT CURRENT_TIME,
  supermercado TEXT NOT NULL,
  categoria TEXT DEFAULT 'Varios',
  total DECIMAL(10,2) NOT NULL,
  ticket_imagen_uri TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Crear la tabla de productos vinculada a una compra (Relación 1 a muchos)
CREATE TABLE productos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  compra_id BIGINT REFERENCES compras(id) ON DELETE CASCADE,
  codigo TEXT,
  nombre TEXT NOT NULL,
  cantidad INTEGER DEFAULT 1,
  precio DECIMAL(10,2) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
