-- SCRIPT SQL PARA SUPABASE
-- Copia y pega esto en el SQL Editor de tu proyecto en Supabase

-- 1. Tabla de Supermercados
CREATE TABLE supermercados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insertar datos iniciales
INSERT INTO supermercados (nombre) VALUES
('Carrefour'),
('Coto'),
('Jumbo'),
('Disco'),
('Vea'),
('Día%'),
('ChangoMás');

-- 2. Tabla de Compras
CREATE TABLE compras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_local INT, -- ID que tenía en el celular
    fecha DATE NOT NULL,
    hora TIME NOT NULL,
    supermercado TEXT NOT NULL,
    total DECIMAL(10,2) NOT NULL,
    categoria TEXT DEFAULT 'Otros', -- Nueva columna para categorizar
    ticket_imagen_uri TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabla de Productos
CREATE TABLE productos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compra_id BIGINT REFERENCES compras(id) ON DELETE CASCADE,
    codigo TEXT,
    nombre TEXT NOT NULL,
    descripcion TEXT,
    cantidad INT NOT NULL,
    precio DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tabla de Presupuestos (Para el Algoritmo del Banquero)
CREATE TABLE presupuestos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria TEXT NOT NULL UNIQUE,
    monto_maximo DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Datos iniciales de presupuesto
INSERT INTO presupuestos (categoria, monto_maximo) VALUES
('Comida', 50000.00),
('Servicios', 30000.00),
('Ocio', 15000.00),
('Otros', 10000.00);
